[package]
name = "forge_all_ides"
version = "0.1.0"
edition = "2021"

[dependencies]
forge_domain = { path = "../forge_domain" }
forge_code = { path = "../forge_code" }
anyhow = "1.0.95"
async-trait = "0.1.85"
