# Production permission configuration
# Secure settings for production environments

permission_config:
  # Default policy - require approval for each operation
  default_policy: Once

  # Strict permission settings
  permissions:
    read:
      policy: Session  # Allow reading files for the session
    write:
      policy: Once    # Require approval for each write
    execute:
      policy: Deny    # No execution allowed

  # Comprehensive security-focused deny patterns
  deny_patterns:
    # Security-sensitive files
    - "**/*.env"
    - "**/*.key"
    - "**/*.pem"
    - "**/secrets/**"
    - "**/security/**"
    
    # Build and dependency directories
    - "**/node_modules/**"
    - "**/target/**"
    - "**/.git/**"
    
    # Cache and temporary files
    - "**/tmp/**"
    - "**/cache/**"
    - "**/.DS_Store"
    
    # Config files
    - "**/config/**"
    - "**/*.conf"
    
    # Log files
    - "**/logs/**"
    - "**/*.log"