[package]
name = "forge_snapshot"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
async-trait = "0.1.87"
sha2 = "0.11.0-pre.4"
tokio = {version = "1.43.0", features = ["fs"]}

[dev-dependencies]
tempfile = "3.17.1"
