[package]
name = "forge_domain"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { version = "1.0.0-beta.6", features = ["from", "error", "display"] }
thiserror = "1.0.56"
url = "2.5.4"
