[package]
name = "forge_domain"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = { version = "1.0.0", features = ["from", "display"] }
derive_setters = "0.1.6"
nom = "7.1.3"
quick-xml = { version = "0.37.2", features = ["serialize"] }
schemars = "0.8.21"
serde = "1.0.217"
serde_json = "1.0.134"
strum = "0.26.3"
strum_macros = "0.26.4"
tokio-stream = "0.1.17"

[dev-dependencies]
insta = { version = "1.34.0", features = ["json"] }
