[package]
name = "forge-outline"
version = "0.1.0"
edition = "2021"

[dependencies]
tree-sitter = "0.20.10"
tree-sitter-javascript = "0.20.1"
tree-sitter-python = "0.20.4"
tree-sitter-rust = "0.20.4"


[dev-dependencies]
tempfile = "3.8.1"
insta = "1.34.0"
