[package]
name = "forge_ci"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
gh-workflow-tailcall = { git = "https://github.com/tailcallhq/rust-gh-workflows", branch = "export-gh-workflow-from-tc-wf" }
serde_json = "1.0.134"
