[package]
name = "forge_code"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
md5 = "0.7.0"
sysinfo = "0.33.1"
bincode = "1.3.3"
tokio = {version = "1.43.0", features = ["macros", "rt"]}
rusqlite = "0.32.1"
serde_json = "1.0.135"
forge_domain = { path = "../forge_domain" }
