[package]
name = "forge-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.83"
derive_more = { version = "1.0.0", features = ["full"] }
nom = "7.1.3"
serde = "1.0.216"
serde_json = "1.0.133"
thiserror = "2.0.8"
tokio = "1.42.0"
tokio-stream = "0.1.17"
forge-provider = { path = "../forge-provider" }
forge-tool ={ path = "../forge-tool" }
derive_setters = "0.1.6"
