name: Release Drafter
on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
  push:
    branches:
    - main
permissions:
  contents: write
  pull-requests: write
jobs:
  update_release_draft:
    name: update_release_draft
    runs-on: ubuntu-latest
    steps:
    - uses: release-drafter/release-drafter@v6
      with:
        commitish: main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
